# Auto-generated by DeepAgent's heal_terraform_state on 2026-08-05T05:51:19Z.
# Cause: run tf_8xa9mttnfqm0 failed because the following AWS resources already
# exist (partial-apply state drift). These 'import' blocks tell Terraform 1.5+
# to adopt them on the next apply. Once state is aligned, this file can be
# deleted — Terraform re-planning without it is a no-op for imported resources.

import {
  to = module.eks.module.kms.aws_kms_alias.this["cluster"]
  id = "alias/eks/dev"
}

import {
  to = module.eks.module.kms.aws_kms_alias.this["cluster"]
  id = "alias/eks/dev"
}

import {
  to = module.eks.aws_cloudwatch_log_group.this[0]
  id = "/aws/eks/dev/cluster"
}

import {
  to = module.eks.aws_cloudwatch_log_group.this[0]
  id = "/aws/eks/dev/cluster"
}
