/**
 * Renders a Trivy remediation doc (from generateRemediationDoc) into a polished,
 * downloadable PDF — entirely client-side via jsPDF, so there's no server PDF
 * dependency. The DevOps lead clicks "Generate remediation doc"; this produces
 * the file they hand to developers, grouped by severity with a concrete fix
 * under each finding.
 */
import type { RemediationDoc } from "./trivy-remediation";

type RGB = [number, number, number];

const SEV_COLOR: Record<string, RGB> = {
  CRITICAL: [183, 28, 28],
  HIGH: [216, 67, 21],
  MEDIUM: [245, 124, 0],
  LOW: [46, 125, 50],
  UNKNOWN: [97, 97, 97],
};

const INK: RGB = [33, 37, 41];
const MUTED: RGB = [110, 116, 124];
const ACCENT: RGB = [21, 101, 192];

function safeName(artifact: string): string {
  const base = (artifact.split("/").pop() || artifact)
    .replace(/[^a-z0-9._-]+/gi, "-")
    .replace(/^-+|-+$/g, "");
  return `${base || "repo"}-security-remediation.pdf`;
}

export async function downloadRemediationPdf(
  doc: RemediationDoc,
  generatedAt: string,
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "a4" });

  const W = pdf.internal.pageSize.getWidth();
  const H = pdf.internal.pageSize.getHeight();
  const M = 44;
  const maxW = W - M * 2;
  let y = M;

  const ensure = (needed: number) => {
    if (y + needed > H - M) {
      pdf.addPage();
      y = M;
    }
  };

  const para = (
    text: string,
    opts: {
      size?: number;
      color?: RGB;
      style?: "normal" | "bold" | "italic";
      gapAfter?: number;
      indent?: number;
    } = {},
  ) => {
    const { size = 10, color = INK, style = "normal", gapAfter = 6, indent = 0 } = opts;
    pdf.setFont("helvetica", style);
    pdf.setFontSize(size);
    pdf.setTextColor(color[0], color[1], color[2]);
    const lh = size * 1.4;
    const lines = pdf.splitTextToSize(text, maxW - indent) as string[];
    for (const line of lines) {
      ensure(lh);
      pdf.text(line, M + indent, y);
      y += lh;
    }
    y += gapAfter;
  };

  // ── Header band ──────────────────────────────────────────────────────────
  pdf.setFillColor(17, 24, 39);
  pdf.rect(0, 0, W, 92, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.text("Security Remediation Guide", M, 44);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(203, 213, 225);
  pdf.text(doc.artifact, M, 64);
  pdf.setFontSize(9);
  pdf.text(
    `Generated ${generatedAt}${doc.aiEnriched ? "  ·  AI-assisted" : "  ·  from scan data"}`,
    M,
    80,
  );
  y = 92 + 24;

  // ── Executive summary ────────────────────────────────────────────────────
  para("Summary", { size: 13, style: "bold", gapAfter: 4 });
  para(doc.summary, { size: 10.5, color: INK, gapAfter: 10 });

  // Severity totals line.
  const totalsLine = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]
    .filter((s) => (doc.counts[s] ?? 0) > 0)
    .map((s) => `${doc.counts[s]} ${s}`)
    .join("    ");
  if (totalsLine) para(totalsLine, { size: 10, color: MUTED, style: "bold", gapAfter: 14 });

  // ── Sections by severity ─────────────────────────────────────────────────
  for (const sec of doc.sections) {
    const color = SEV_COLOR[sec.severity] ?? MUTED;
    ensure(60);
    // Severity heading bar.
    pdf.setFillColor(color[0], color[1], color[2]);
    pdf.rect(M, y - 12, maxW, 22, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.text(
      `${sec.severity}  —  ${sec.items.length} issue${sec.items.length === 1 ? "" : "s"}`,
      M + 8,
      y + 3,
    );
    y += 22;

    para(sec.overview, { size: 9.5, color: MUTED, style: "italic", gapAfter: 8 });

    sec.items.forEach((it, i) => {
      ensure(48);
      // Title line: "1. CVE-XXXX — title"
      const head = `${i + 1}. ${it.id}${it.title ? ` — ${it.title}` : ""}`;
      para(head, { size: 10, style: "bold", gapAfter: 2 });

      // Meta line: type · where · pkg installed → fixed
      const bits: string[] = [it.cls];
      if (it.where) bits.push(it.where);
      if (it.pkg) {
        const ver = it.installed ? `${it.pkg} ${it.installed}` : it.pkg;
        bits.push(it.fixedVersion ? `${ver} → ${it.fixedVersion}` : ver);
      }
      para(bits.join("   ·   "), { size: 8.8, color: MUTED, gapAfter: 3, indent: 12 });

      // The fix.
      para(`Fix:  ${it.recommendation}`, { size: 9.6, color: ACCENT, gapAfter: 12, indent: 12 });
    });
  }

  // ── Footer page numbers ──────────────────────────────────────────────────
  const pages = pdf.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    pdf.setPage(p);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(MUTED[0], MUTED[1], MUTED[2]);
    pdf.text("Generated by DeepAgent — share with the developers who own this repo.", M, H - 24);
    pdf.text(`Page ${p} of ${pages}`, W - M, H - 24, { align: "right" });
  }

  pdf.save(safeName(doc.artifact));
}
