import { NextResponse } from "next/server";
import { z } from "zod";
import forge from "node-forge";
import { prisma } from "@/lib/db/prisma";
import { requireProjectAccess } from "@/lib/projects/permissions";
import { buildAzureVpnTerraform, validateAzureVpnCidr, AZURE_VPN_DEFAULTS } from "@/lib/devops/azure-openvpn";
import { createInfraApproval, type TerraformFile } from "@/lib/devops/infra-approval";
import { writeRepoFileTool } from "@/lib/agent/tools/write-repo-file";
import { encryptSecret } from "@/lib/auth/crypto";

/**
 * POST /projects/[slug]/azure/vpn — self-hosted OpenVPN on a small Azure VM.
 *
 * Mirrors /aws/client-vpn + /gcp/vpn — commits Terraform to the repo, creates
 * an infra approval. Apply runs via the shared run_terraform pipeline.
 */
const Body = z.object({
  name: z
    .string()
    .trim()
    .regex(/^[a-z][a-z0-9-]{1,40}$/, "Name must be lowercase, dashes, 2-41 chars, starting with a letter."),
  envKey: z.string().trim().min(1),
  location: z.string().trim().min(1),
  resourceGroupName: z.string().trim().min(1),
  vnetName: z.string().trim().min(1),
  subnetName: z.string().trim().min(1),
  vpcCidr: z.string().trim().min(1),
  vmSize: z.string().trim().optional(),
  diskGb: z.number().int().min(30).max(200).optional(),
  clientCidr: z.string().trim().optional(),
  certOwnerName: z.string().trim().max(60).optional(),
  splitTunnel: z.boolean().optional(),
  transportProtocol: z.enum(["udp", "tcp"]).optional(),
  vpnPort: z.union([z.literal(1194), z.literal(443)]).optional(),
  sourceRanges: z.array(z.string().trim().min(1)).max(20).optional(),
  adminUsername: z.string().trim().optional(),
  // Optional — when absent (the wizard's default), we auto-generate an RSA-2048
  // OpenSSH keypair server-side, encrypt the private key with AES-256-GCM, and
  // stash it in the approval's payloadJson so the user can download it later.
  // Matches the app-fully-self-contained pattern — no ssh-keygen on the user's
  // laptop.
  sshPublicKey: z.string().trim().optional(),
});

export async function POST(req: Request, ctx: { params: Promise<{ slug: string }> }) {
  const { slug } = await ctx.params;
  const gate = await requireProjectAccess(slug, "developer");
  if (!gate.ok) return NextResponse.json({ ok: false }, { status: gate.status });
  const projectId = gate.access.project.id;

  const parsed = Body.safeParse(await req.json().catch(() => ({})));
  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, code: "invalid_request", message: parsed.error.errors[0]?.message },
      { status: 400 },
    );
  }
  const body = parsed.data;
  const clientCidr = body.clientCidr ?? AZURE_VPN_DEFAULTS.clientCidr;
  const cidrCheck = validateAzureVpnCidr(clientCidr);
  if (!cidrCheck.ok) {
    return NextResponse.json(
      { ok: false, code: "invalid_cidr", message: `clientCidr: ${cidrCheck.error}` },
      { status: 400 },
    );
  }

  const cp = await prisma.cloudProvider.findFirst({
    where: { projectId, kind: "azure" },
    select: { id: true },
  });
  if (!cp) return NextResponse.json({ ok: false, code: "no_azure_provider" }, { status: 409 });
  const env = await prisma.env.findFirst({
    where: { projectId, key: body.envKey },
    select: { id: true, key: true },
  });
  if (!env) return NextResponse.json({ ok: false, code: "env_not_found" }, { status: 404 });
  const pr = await prisma.projectRepo.findFirst({
    where: { projectId, repo: { deletedAt: null } },
    orderBy: { addedAt: "desc" },
    select: { repo: { select: { fullName: true, defaultBranch: true } } },
  });
  if (!pr?.repo?.fullName) {
    return NextResponse.json({ ok: false, code: "no_repo", message: "Attach a repo first." }, { status: 409 });
  }
  const repoFullName = pr.repo.fullName;
  const defaultBranch = pr.repo.defaultBranch || "main";

  // Auto-generate an admin SSH keypair when the caller didn't paste one.
  // Node-forge gives us the OpenSSH pub-format Azure's ssh_public_key field
  // needs, and PEM-format private for the .pem download. Both are stashed
  // encrypted in the approval's payloadJson (see below) so the user can
  // grab the private key from the app later — never leaves the server plaintext.
  let adminSshPublicKey = body.sshPublicKey?.trim();
  let adminSshPrivateKeyPem: string | null = null;
  const adminSshAutoGenerated = !adminSshPublicKey;
  if (adminSshAutoGenerated) {
    const keys = forge.pki.rsa.generateKeyPair(2048);
    const comment = `${body.name}-azure-vpn-admin`;
    adminSshPublicKey = forge.ssh.publicKeyToOpenSSH(keys.publicKey, comment).trim();
    adminSshPrivateKeyPem = forge.ssh.privateKeyToOpenSSH(keys.privateKey);
  }

  const files = buildAzureVpnTerraform({
    name: body.name,
    location: body.location,
    env: body.envKey,
    resourceGroupName: body.resourceGroupName,
    vnetName: body.vnetName,
    subnetName: body.subnetName,
    vpcCidr: body.vpcCidr,
    vmSize: body.vmSize,
    diskGb: body.diskGb,
    clientCidr,
    certOwnerName: body.certOwnerName,
    splitTunnel: body.splitTunnel,
    transportProtocol: body.transportProtocol,
    vpnPort: body.vpnPort,
    sourceRanges: body.sourceRanges,
    adminUsername: body.adminUsername,
    sshPublicKey: adminSshPublicKey!,
    tags: { CreatedBy: "deepagent-azure-vpn-ui" },
  });

  const commits: Array<{ path: string; commitSha: string }> = [];
  for (const [filename, content] of Object.entries(files)) {
    const path = `terraform/azure-vpn/${body.name}/${filename}`;
    const res = await writeRepoFileTool.execute(
      {
        repoFullName,
        path,
        content,
        message: `Add Azure OpenVPN ${body.name} (${body.location})`,
        branch: defaultBranch,
      },
      { projectId, userId: gate.access.session.userId },
    );
    if (!res.ok) {
      return NextResponse.json(
        { ok: false, code: "commit_failed", message: `${path}: ${res.error}` },
        { status: 502 },
      );
    }
    commits.push({ path, commitSha: res.output.commitSha });
  }

  // Stack prefix `azure-vpn-` — the cert-issuance endpoints branch on this
  // to know how to build the .ovpn base (there's no equivalent to AWS's
  // export-client-vpn-client-configuration for self-hosted OpenVPN, so we
  // build the header from the endpoint's public IP + port).
  const stack = `azure-vpn-${body.name}`;
  const tfFiles: TerraformFile[] = Object.entries(files).map(([path, content]) => ({ path, content }));
  const planSummary = [
    { change: "add" as const, text: `azurerm_linux_virtual_machine ${body.name}-openvpn (${body.vmSize ?? "Standard_B1s"})` },
    { change: "add" as const, text: `azurerm_public_ip ${body.name}-openvpn-pip (Static)` },
    { change: "add" as const, text: `azurerm_network_security_group + NIC + assoc` },
    { change: "add" as const, text: "tls_* resources (CA + server + initial client certs auto-generated)" },
  ];
  if (body.splitTunnel === false) {
    planSummary.push({ change: "add" as const, text: "full-tunnel mode — client's ALL internet traffic goes through this VM" });
  }

  const approval = await createInfraApproval({
    projectId,
    envId: env.id,
    envKey: env.key,
    title: `Create Azure OpenVPN ${body.name} in ${body.location}`,
    summary: `Self-hosted OpenVPN endpoint on ${body.vnetName}/${body.subnetName} (${body.vpcCidr}) in RG ${body.resourceGroupName}. Client CIDR ${clientCidr}. ~$13/mo (Standard_B1s + static IP).`,
    cloud: "azure",
    region: body.location,
    name: `${stack}-apply`,
    stack,
    files: tfFiles,
    planSummary,
  });
  if (!approval.ok) {
    return NextResponse.json(
      {
        ok: false,
        code: "policy_blocked",
        message: `Policy blocked this change: ${approval.policy.violations.map((v) => v.message).join(" ")}`,
        violations: approval.policy.violations,
      },
      { status: 400 },
    );
  }

  // Stash the auto-generated admin SSH keypair on the approval so the app can
  // hand the private key back to the user via the admin-ssh-key download
  // endpoint. Private key is AES-256-GCM encrypted; public key is stored in
  // plaintext (it's already in the terraform files anyway).
  if (adminSshAutoGenerated && adminSshPrivateKeyPem) {
    const existing = await prisma.approval.findUnique({
      where: { id: approval.approvalId },
      select: { payloadJson: true },
    });
    const merged = {
      ...((existing?.payloadJson ?? {}) as Record<string, unknown>),
      _adminSshKey: {
        privateKeyEnc: encryptSecret(adminSshPrivateKeyPem),
        publicKey: adminSshPublicKey,
        adminUsername: body.adminUsername ?? "azureuser",
        generatedAt: new Date().toISOString(),
      },
    };
    await prisma.approval.update({
      where: { id: approval.approvalId },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      data: { payloadJson: merged as any },
    });
  }

  return NextResponse.json({
    ok: true,
    approvalId: approval.approvalId,
    risk: approval.risk,
    committedFiles: commits,
    repoPath: `terraform/azure-vpn/${body.name}/`,
    repoFullName,
    adminSshAutoGenerated,
  });
}
