"use client";

/**
 * Azure OpenVPN endpoint launch wizard, embedded in chat via the
 * ```azure-vpn-create``` fence. Self-hosted OpenVPN on a Standard_B1s VM
 * (~$13/mo) vs Azure's managed VPN Gateway at ~$140/mo. Same shape as
 * GcpVpnCreateBox.
 */
import { useEffect, useMemo, useState } from "react";
import { Block, Btn, Field, Input, Select, type SelectOption } from "@/components/ui";
import { ApprovalCard } from "@/components/domain/ApprovalCard";
import { useProjectEnvs } from "@/hooks/queries/project";
import {
  useAzureAvailableVmSizes,
  useAzureVnetsInLocation,
  useAzureVpnList,
  useSubmitAzureVpn,
} from "@/hooks/queries/network";
import { AZURE_LOCATIONS } from "@/lib/azure-locations";

type Answers = {
  name: string;
  location: string;
  envKey: string;
  resourceGroupName: string;
  vnetName: string;
  subnetName: string;
  vpcCidr: string;
  vmSize: string;
  clientCidr: string;
  certOwnerName: string;
  splitTunnel: boolean;
  transportProtocol: "udp" | "tcp";
  vpnPort: 1194 | 443;
  sourceRanges: string;
  adminUsername: string;
  // The wizard no longer collects an SSH pubkey — the server auto-generates
  // an RSA-2048 keypair. Field kept in state for the (rare) advanced case
  // where a user wants to paste their own, but the UI omits the input.
  sshPublicKey: string;
};

const PAGE_TITLES = ["Name & location", "VNet & subnet", "Tunnel & certs", "Review"];

// FALLBACK size list — used only if the live /azure/vm-sizes API is
// unreachable. Normally the wizard queries the user's actual quota +
// region availability and only lists what they can provision.
const FALLBACK_SIZE_OPTIONS: SelectOption[] = [
  // ── B-series v1 (burstable, cheapest — quota family: standardBsFamily) ──
  { value: "Standard_B1s", label: "Standard_B1s — 1 vCPU / 1 GB (~$8/mo, default; cheapest, B-series v1)" },
  { value: "Standard_B1ms", label: "Standard_B1ms — 1 vCPU / 2 GB (~$15/mo, B-series v1)" },
  { value: "Standard_B2s", label: "Standard_B2s — 2 vCPU / 4 GB (~$30/mo, B-series v1, plenty for teams)" },
  { value: "Standard_B2ms", label: "Standard_B2ms — 2 vCPU / 8 GB (~$60/mo, B-series v1)" },
  // ── B-series v2 (burstable, newer — quota family: standardBasv2Family) ──
  { value: "Standard_B2ats_v2", label: "Standard_B2ats_v2 — 2 vCPU / 1 GB (~$15/mo, B-series v2)" },
  { value: "Standard_B2als_v2", label: "Standard_B2als_v2 — 2 vCPU / 4 GB (~$30/mo, B-series v2)" },
  // ── D-series v3/v5 (general purpose — quota families usually allocated) ──
  { value: "Standard_D2s_v3", label: "Standard_D2s_v3 — 2 vCPU / 8 GB (~$70/mo, general purpose, D-series v3 — usually always available)" },
  { value: "Standard_D2s_v5", label: "Standard_D2s_v5 — 2 vCPU / 8 GB (~$70/mo, D-series v5)" },
  { value: "Standard_D2as_v5", label: "Standard_D2as_v5 — 2 vCPU / 8 GB (~$65/mo, AMD, D-series v5)" },
  { value: "Standard_D2ads_v5", label: "Standard_D2ads_v5 — 2 vCPU / 8 GB (~$85/mo, D-series v5 with local SSD)" },
  { value: "Standard_D4s_v5", label: "Standard_D4s_v5 — 4 vCPU / 16 GB (~$140/mo, D-series v5)" },
  // ── DS-series v2 (older, near-universal quota — last-resort reliable) ──
  { value: "Standard_DS1_v2", label: "Standard_DS1_v2 — 1 vCPU / 3.5 GB (~$50/mo, older DS-series v2 — most reliable quota)" },
  { value: "Standard_DS2_v2", label: "Standard_DS2_v2 — 2 vCPU / 7 GB (~$100/mo, DS-series v2)" },
];

export function AzureVpnCreateBox({ slug }: { slug: string }) {
  const { data: envs } = useProjectEnvs(slug);
  const submit = useSubmitAzureVpn(slug);

  const [answers, setAnswers] = useState<Answers>({
    name: "team-vpn",
    location: "eastus",
    envKey: "",
    resourceGroupName: "",
    vnetName: "",
    subnetName: "",
    vpcCidr: "",
    vmSize: "Standard_B1s",
    clientCidr: "10.100.0.0/22",
    certOwnerName: "",
    splitTunnel: true,
    transportProtocol: "udp",
    vpnPort: 1194,
    sourceRanges: "0.0.0.0/0",
    adminUsername: "azureuser",
    sshPublicKey: "",
  });
  const [pageIdx, setPageIdx] = useState(0);
  const [serverError, setServerError] = useState<string | null>(null);
  const [result, setResult] = useState<{
    approvalId: string;
    repoPath: string;
    repoFullName: string;
    adminSshAutoGenerated?: boolean;
  } | null>(null);
  const [sshDownloading, setSshDownloading] = useState(false);
  const [sshError, setSshError] = useState<string | null>(null);
  const [vpnDownloading, setVpnDownloading] = useState(false);
  const [vpnError, setVpnError] = useState<string | null>(null);

  const vnetsQuery = useAzureVnetsInLocation(slug, answers.location || null);
  const vmSizesQuery = useAzureAvailableVmSizes(slug, answers.location || null);

  useEffect(() => {
    if (answers.envKey || !envs?.length) return;
    setAnswers((a) => ({ ...a, envKey: envs[0]!.key }));
  }, [envs, answers.envKey]);

  // When VNet changes, auto-fill resource group + reset subnet.
  useEffect(() => {
    const vnets = vnetsQuery.data && "vnets" in vnetsQuery.data ? vnetsQuery.data.vnets : [];
    const picked = vnets.find((v) => v.name === answers.vnetName);
    if (picked && picked.resourceGroup !== answers.resourceGroupName) {
      setAnswers((a) => ({ ...a, resourceGroupName: picked.resourceGroup, subnetName: "", vpcCidr: "" }));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [answers.vnetName, vnetsQuery.data]);

  const envOptions: SelectOption[] = (envs ?? []).map((e) => ({ value: e.key, label: e.name || e.key }));
  const locationOptions: SelectOption[] = useMemo(() => AZURE_LOCATIONS.map((l) => ({ value: l, label: l })), []);
  const vnets = vnetsQuery.data && "vnets" in vnetsQuery.data ? vnetsQuery.data.vnets : [];
  const vnetOptions: SelectOption[] = vnets.map((v) => ({ value: v.name, label: `${v.name} · ${v.resourceGroup} · ${v.addressSpace.join(", ")}` }));
  const pickedVnet = vnets.find((v) => v.name === answers.vnetName);
  const subnetOptions: SelectOption[] = (pickedVnet?.subnets ?? []).map((s) => ({ value: s.name, label: `${s.name} · ${s.addressPrefix}` }));

  // Live VM sizes filtered by (a) region availability + (b) user's quota.
  // Falls back to the hardcoded FALLBACK_SIZE_OPTIONS only if the API errors.
  const availableSizes = vmSizesQuery.data?.available ?? [];
  const unavailableSizes = vmSizesQuery.data?.unavailable ?? [];
  const recommendedSize = vmSizesQuery.data?.recommendedVmSize ?? null;
  // Sort by reliability (desc), then cost (asc). Reliability is our defence
  // against Azure's own API lying about capacity — B-series says "available"
  // in the SKUs API but 409s at create-time roughly half the time in busy
  // regions. D-series is nearly always deployable. Users see reliable-first.
  const sizeOptions: SelectOption[] = availableSizes.length
    ? availableSizes
        .slice()
        .sort((a, b) => {
          if (b.reliability !== a.reliability) return b.reliability - a.reliability;
          return a.monthlyCost - b.monthlyCost;
        })
        .map((s) => ({
          value: s.vmSize,
          label: `${s.vmSize} — ${s.vCPUs} vCPU / ${s.memoryGB} GB (~$${s.monthlyCost}/mo${s.notes ? `, ${s.notes}` : ""})`,
        }))
    : FALLBACK_SIZE_OPTIONS;

  // Auto-pick the recommended (cheapest available) size when the API comes back.
  useEffect(() => {
    if (!recommendedSize) return;
    // Only switch if the current pick is unavailable, so we don't overwrite
    // a deliberate user choice.
    const stillOk = availableSizes.some((s) => s.vmSize === answers.vmSize);
    if (!stillOk) setAnswers((a) => ({ ...a, vmSize: recommendedSize }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [recommendedSize, availableSizes.length]);

  // Auto-fill vpcCidr from the picked subnet — the "reach the VPC" route
  // needs the subnet CIDR, and the wizard shouldn't force the user to look
  // it up manually when it's already in the subnet metadata.
  useEffect(() => {
    if (!answers.subnetName || !pickedVnet) return;
    const s = pickedVnet.subnets.find((s) => s.name === answers.subnetName);
    if (s?.addressPrefix && s.addressPrefix !== answers.vpcCidr) {
      setAnswers((a) => ({ ...a, vpcCidr: s.addressPrefix }));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [answers.subnetName, pickedVnet]);

  const errors: Partial<Record<keyof Answers, string>> = {};
  if (pageIdx === 0) {
    if (!/^[a-z][a-z0-9-]{1,40}$/.test(answers.name.trim())) errors.name = "Lowercase, dashes, 2-41 chars.";
    if (!answers.location) errors.location = "Pick a location.";
    if (!answers.envKey) errors.envKey = "Pick an env.";
  }
  if (pageIdx === 1) {
    if (!answers.vnetName) errors.vnetName = "Pick a VNet.";
    if (!answers.subnetName) errors.subnetName = "Pick a subnet.";
    if (!answers.vpcCidr) errors.vpcCidr = "Subnet CIDR required (auto-filled from the picked subnet).";
  }
  if (pageIdx === 2) {
    const cidrRe = /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}$/;
    if (!cidrRe.test(answers.clientCidr.trim())) errors.clientCidr = "Not a valid IPv4 CIDR (e.g. 10.100.0.0/22).";
    for (const r of answers.sourceRanges.split(",").map((s) => s.trim()).filter(Boolean)) {
      if (!cidrRe.test(r)) {
        errors.sourceRanges = `"${r}" is not a valid CIDR.`;
        break;
      }
    }
    if (!answers.adminUsername.trim()) errors.adminUsername = "Required.";
    // sshPublicKey deliberately NOT required — the server auto-generates it.
  }
  const pageHasError = Object.keys(errors).length > 0;
  const onReview = pageIdx === PAGE_TITLES.length - 1;

  async function handleCreate() {
    setServerError(null);
    try {
      const sourceRanges = answers.sourceRanges
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      const res = await submit.mutateAsync({
        name: answers.name.trim(),
        envKey: answers.envKey,
        location: answers.location,
        resourceGroupName: answers.resourceGroupName,
        vnetName: answers.vnetName,
        subnetName: answers.subnetName,
        vpcCidr: answers.vpcCidr,
        vmSize: answers.vmSize,
        clientCidr: answers.clientCidr.trim(),
        certOwnerName: answers.certOwnerName.trim() || undefined,
        splitTunnel: answers.splitTunnel,
        transportProtocol: answers.transportProtocol,
        vpnPort: answers.vpnPort,
        sourceRanges: sourceRanges.length ? sourceRanges : undefined,
        adminUsername: answers.adminUsername.trim(),
        // Empty string = server auto-generates the keypair. Kept as an escape
        // hatch for advanced users who want their own key on the VM.
        sshPublicKey: answers.sshPublicKey.trim() || "",
      });
      if (res.approvalId) {
        setResult({
          approvalId: res.approvalId,
          repoPath: res.repoPath ?? "",
          repoFullName: res.repoFullName ?? "",
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          adminSshAutoGenerated: (res as any).adminSshAutoGenerated ?? !answers.sshPublicKey.trim(),
        });
      }
    } catch (e) {
      setServerError(e instanceof Error ? e.message : "Azure VPN submit failed.");
    }
  }

  async function downloadAdminSshKey() {
    if (!result) return;
    setSshError(null);
    setSshDownloading(true);
    try {
      const res = await fetch(`/api/v1/projects/${slug}/azure/vpn/${result.approvalId}/admin-ssh-key`, { cache: "no-store" });
      if (!res.ok) {
        const body = (await res.json().catch(() => ({}))) as { message?: string };
        throw new Error(body.message ?? `Download failed (${res.status}).`);
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `azure-vpn-${answers.name}-admin-ssh.zip`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (e) {
      setSshError(e instanceof Error ? e.message : "Download failed.");
    } finally {
      setSshDownloading(false);
    }
  }

  // POSTs to the initial-cert endpoint which pulls the auto-generated client
  // cert + key + CA + endpoint DNS from terraform state, assembles a self-
  // contained .ovpn file, persists to VpnUserCert (userName="initial") so it
  // shows up in the sidebar's Client VPN page, and streams a zip. Only works
  // after the apply completes — the state has to exist.
  async function downloadInitialCert() {
    if (!result) return;
    setVpnError(null);
    setVpnDownloading(true);
    try {
      const res = await fetch(`/api/v1/projects/${slug}/azure/vpn/${result.approvalId}/initial-cert`, {
        method: "POST",
        cache: "no-store",
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => ({}))) as { message?: string };
        throw new Error(body.message ?? `Download failed (${res.status}).`);
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `azure-vpn-${answers.name}-initial.zip`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (e) {
      setVpnError(e instanceof Error ? e.message : "Download failed.");
    } finally {
      setVpnDownloading(false);
    }
  }

  // Poll the Azure VPN list to know when THIS approval's apply has actually
  // succeeded — only then does the terraform state exist + the download
  // endpoint can pull the cert PEMs. The list hook has staleTime 30s; we
  // trigger a refetch every 15s while we're still waiting.
  const vpnListForResult = useAzureVpnList(slug);
  useEffect(() => {
    if (!result) return;
    const matched = vpnListForResult.data?.items?.find((it) => it.approvalId === result.approvalId);
    if (matched?.appliedAt) return; // Applied — stop polling.
    const t = setInterval(() => vpnListForResult.refetch(), 15_000);
    return () => clearInterval(t);
  }, [result, vpnListForResult]);
  const applyStatus = result
    ? vpnListForResult.data?.items?.find((it) => it.approvalId === result.approvalId)
    : null;
  const isApplied = !!applyStatus?.appliedAt;
  const applyStatusLabel = !applyStatus
    ? "waiting for approval…"
    : applyStatus.status === "approved" && !applyStatus.appliedAt
    ? "approved — terraform apply running…"
    : applyStatus.appliedAt
    ? "apply complete"
    : applyStatus.status;

  if (result) {
    return (
      <Block>
        <Block.Header>
          <Block.Title sub={`Files committed to ${result.repoFullName}/${result.repoPath}. Approve to run terraform apply.`}>
            Azure OpenVPN submitted — pending approval
          </Block.Title>
        </Block.Header>
        <Block.Body>
          <div className="col gap-3">
            <div className="col gap-2" style={{ padding: 12, borderRadius: 8, border: "1px solid var(--border)" }}>
              <div className="row between" style={{ alignItems: "center", gap: 12 }}>
                <div className="col gap-1" style={{ minWidth: 0, flex: 1 }}>
                  <span style={{ fontWeight: 600, fontSize: 13 }}>Client .ovpn bundle</span>
                  <span className="muted" style={{ fontSize: 12 }}>
                    {isApplied
                      ? "Ready. Download the .ovpn (cert + key + CA embedded) — import into Tunnelblick / OpenVPN Connect and connect. Also saved to the Client VPN sidebar for re-download."
                      : `Status: ${applyStatusLabel}. Download unlocks once terraform apply succeeds — polls every 15s. If apply fails in the infra tab, this stays disabled (no cert to download).`}
                  </span>
                </div>
                <Btn
                  variant="primary"
                  icon="download"
                  onClick={downloadInitialCert}
                  loading={vpnDownloading}
                  disabled={!isApplied}
                >
                  {isApplied ? "Download .ovpn" : "Waiting for apply…"}
                </Btn>
              </div>
              {vpnError && <p style={{ fontSize: 12, color: "var(--danger)" }} role="alert">{vpnError}</p>}
            </div>
            {result.adminSshAutoGenerated && (
              <div className="col gap-2" style={{ padding: 12, borderRadius: 8, border: "1px solid var(--border)" }}>
                <div className="row between" style={{ alignItems: "center", gap: 12 }}>
                  <div className="col gap-1" style={{ minWidth: 0, flex: 1 }}>
                    <span style={{ fontWeight: 600, fontSize: 13 }}>Admin SSH key ready</span>
                    <span className="muted" style={{ fontSize: 12 }}>
                      Auto-generated RSA-2048 keypair. Download it now (or later — it's saved with the approval). Only needed if you ever want to SSH the VPN VM for debugging.
                    </span>
                  </div>
                  <Btn variant="outline" icon="download" onClick={downloadAdminSshKey} loading={sshDownloading}>
                    Download SSH key
                  </Btn>
                </div>
                {sshError && <p style={{ fontSize: 12, color: "var(--danger)" }} role="alert">{sshError}</p>}
              </div>
            )}
            <ApprovalCard slug={slug} approvalId={result.approvalId} />
          </div>
        </Block.Body>
      </Block>
    );
  }

  return (
    <Block>
      <Block.Header>
        <Block.Title sub="Self-hosted OpenVPN on a Standard_B1s VM (~$13/mo). Managed Azure VPN Gateway costs ~$140/mo — we skip it. Same .ovpn download UX as AWS.">
          Create Azure OpenVPN endpoint
        </Block.Title>
      </Block.Header>
      <Block.Body>
        <div className="col gap-4" style={{ maxWidth: 680 }}>
          <div className="row gap-2" style={{ alignItems: "center" }}>
            {PAGE_TITLES.map((_, i) => (
              <span key={i} style={{ flex: 1, height: 4, borderRadius: 2, background: i <= pageIdx ? "var(--accent, #5b8cff)" : "var(--surface-3, #00000018)" }} />
            ))}
          </div>
          <span className="muted" style={{ fontSize: 12.5, fontWeight: 600 }}>
            Step {pageIdx + 1} of {PAGE_TITLES.length} · {PAGE_TITLES[pageIdx]}
          </span>

          {pageIdx === 0 && (
            <div className="col gap-3">
              <Field label="Name" required error={errors.name}>
                <Input value={answers.name} onChange={(e) => setAnswers((a) => ({ ...a, name: e.target.value }))} className="mono" />
              </Field>
              <Field label="Location" required error={errors.location}>
                <Select options={locationOptions} value={answers.location} onValueChange={(v) => setAnswers((a) => ({ ...a, location: v, vnetName: "", subnetName: "", resourceGroupName: "", vpcCidr: "" }))} ariaLabel="Location" />
              </Field>
              <Field label="Environment" required error={errors.envKey}>
                <Select options={envOptions} value={answers.envKey} onValueChange={(v) => setAnswers((a) => ({ ...a, envKey: v }))} ariaLabel="Env" placeholder="Pick an env…" />
              </Field>
            </div>
          )}

          {pageIdx === 1 && (
            <div className="col gap-3">
              <Field
                label="VNet"
                required
                error={errors.vnetName}
                hint={
                  vnetsQuery.isLoading
                    ? "Loading VNets…"
                    : vnets.length === 0
                    ? `No VNets in ${answers.location}. Create one first (say 'create azure vnet').`
                    : `${vnets.length} VNet${vnets.length === 1 ? "" : "s"} in ${answers.location}. RG auto-fills from the pick.`
                }
              >
                <Select options={vnetOptions} value={answers.vnetName} onValueChange={(v) => setAnswers((a) => ({ ...a, vnetName: v, subnetName: "", vpcCidr: "" }))} ariaLabel="VNet" placeholder="Pick a VNet…" disabled={vnetOptions.length === 0} />
              </Field>
              <Field label="Subnet" required error={errors.subnetName} hint={!answers.vnetName ? "Pick a VNet first." : `${subnetOptions.length} subnet${subnetOptions.length === 1 ? "" : "s"} in this VNet.`}>
                <Select options={subnetOptions} value={answers.subnetName} onValueChange={(v) => setAnswers((a) => ({ ...a, subnetName: v }))} ariaLabel="Subnet" placeholder="Pick a subnet…" disabled={!answers.vnetName || subnetOptions.length === 0} />
              </Field>
              {answers.resourceGroupName && (
                <div className="muted" style={{ fontSize: 12 }}>Resource group: <span className="mono">{answers.resourceGroupName}</span></div>
              )}
              <Field label="Subnet CIDR (auto-filled)" hint="Advertised to VPN clients so they can reach VMs on this subnet.">
                <Input value={answers.vpcCidr} onChange={(e) => setAnswers((a) => ({ ...a, vpcCidr: e.target.value }))} className="mono" placeholder="10.0.0.0/24" />
              </Field>
            </div>
          )}

          {pageIdx === 2 && (
            <div className="col gap-3">
              <Field label="Cert owner name" hint="Used as the CN prefix on the CA + server + initial client cert. Leave blank to use the endpoint name.">
                <Input value={answers.certOwnerName} onChange={(e) => setAnswers((a) => ({ ...a, certOwnerName: e.target.value }))} className="mono" placeholder={answers.name} />
              </Field>
              <Field
                label="VM size"
                hint={
                  vmSizesQuery.isLoading
                    ? `Checking your Azure quota + availability in ${answers.location}…`
                    : vmSizesQuery.data?.note
                    ? vmSizesQuery.data.note
                    : availableSizes.length === 0
                    ? `No VM sizes available in ${answers.location} — check your subscription's quota (Portal → Usage + quotas) or try a different region.`
                    : `${availableSizes.length} size${availableSizes.length === 1 ? "" : "s"} available in ${answers.location} — filtered live by your Azure quota. Recommended: ${recommendedSize ?? "—"}.`
                }
              >
                <Select
                  options={sizeOptions}
                  value={answers.vmSize}
                  onValueChange={(v) => setAnswers((a) => ({ ...a, vmSize: v }))}
                  ariaLabel="VM size"
                  disabled={vmSizesQuery.isLoading || sizeOptions.length === 0}
                />
              </Field>
              {unavailableSizes.length > 0 && (
                <details style={{ fontSize: 12, marginTop: -4 }}>
                  <summary className="muted" style={{ cursor: "pointer" }}>
                    Why some sizes are hidden ({unavailableSizes.length})
                  </summary>
                  <ul className="muted" style={{ margin: "6px 0 0 16px", paddingLeft: 0 }}>
                    {unavailableSizes.slice(0, 8).map((u) => (
                      <li key={u.vmSize} style={{ marginBottom: 2 }}>
                        <span className="mono">{u.vmSize}</span> — {u.detail}
                      </li>
                    ))}
                    {unavailableSizes.length > 8 && <li>… and {unavailableSizes.length - 8} more.</li>}
                  </ul>
                </details>
              )}
              <Field label="Client CIDR" required error={errors.clientCidr} hint="Pool of IPs assigned to connected clients. Must not overlap with your VNet address space.">
                <Input value={answers.clientCidr} onChange={(e) => setAnswers((a) => ({ ...a, clientCidr: e.target.value }))} className="mono" />
              </Field>
              <Field label="Transport">
                <Select
                  options={[
                    { value: "udp", label: "UDP (default, faster)" },
                    { value: "tcp", label: "TCP (slower, works through more restrictive firewalls)" },
                  ]}
                  value={answers.transportProtocol}
                  onValueChange={(v) => setAnswers((a) => ({ ...a, transportProtocol: v as "udp" | "tcp" }))}
                  ariaLabel="Transport"
                />
              </Field>
              <Field label="Port">
                <Select
                  options={[
                    { value: "1194", label: "1194 (default OpenVPN port)" },
                    { value: "443", label: "443 (TCP only — blends with HTTPS on restrictive networks)" },
                  ]}
                  value={String(answers.vpnPort)}
                  onValueChange={(v) => setAnswers((a) => ({ ...a, vpnPort: Number(v) as 1194 | 443 }))}
                  ariaLabel="Port"
                />
              </Field>
              <label className="row gap-2" style={{ fontSize: 13, cursor: "pointer" }}>
                <input type="checkbox" checked={answers.splitTunnel} onChange={(e) => setAnswers((a) => ({ ...a, splitTunnel: e.target.checked }))} />
                <span>Split-tunnel (only VNet traffic goes through the VPN — recommended)</span>
              </label>
              <Field label="Source IP ranges" error={errors.sourceRanges} hint="Comma-separated CIDRs allowed to connect. Cert auth still gates access; this is an extra layer.">
                <Input value={answers.sourceRanges} onChange={(e) => setAnswers((a) => ({ ...a, sourceRanges: e.target.value }))} className="mono" placeholder="0.0.0.0/0" />
              </Field>
              <Field label="Admin username" required error={errors.adminUsername} hint="For SSH into the VPN VM if you ever need to debug. NOT the VPN client username.">
                <Input value={answers.adminUsername} onChange={(e) => setAnswers((a) => ({ ...a, adminUsername: e.target.value }))} className="mono" />
              </Field>
              <div className="col gap-1" style={{ padding: 10, borderRadius: 8, background: "var(--surface-2, #00000010)", fontSize: 12.5 }}>
                <span style={{ fontWeight: 600 }}>Admin SSH key — auto-generated</span>
                <span className="muted">
                  The app generates a fresh SSH keypair for the VPN VM. You'll get a download link on the next screen. VPN clients don't use SSH — this is admin-only.
                </span>
              </div>
            </div>
          )}

          {onReview && (
            <div className="col gap-3">
              <div className="col gap-1" style={{ border: "1px solid var(--border)", borderRadius: 8, padding: 12 }}>
                <ReviewRow label="Name" value={answers.name} />
                <ReviewRow label="Location" value={answers.location} />
                <ReviewRow label="Environment" value={envs?.find((e) => e.key === answers.envKey)?.name ?? answers.envKey} />
                <ReviewRow label="Resource group" value={answers.resourceGroupName || "(will resolve from VNet)"} />
                <ReviewRow label="VNet / subnet" value={`${answers.vnetName} / ${answers.subnetName}`} />
                <ReviewRow label="Subnet CIDR" value={answers.vpcCidr || "(missing)"} />
                <ReviewRow label="VM size" value={answers.vmSize} />
                <ReviewRow label="Client CIDR" value={answers.clientCidr} />
                <ReviewRow label="Transport / port" value={`${answers.transportProtocol.toUpperCase()}/${answers.vpnPort}`} />
                <ReviewRow label="Tunnel mode" value={answers.splitTunnel ? "split (VNet only)" : "full (all client traffic)"} />
                <ReviewRow label="Cert owner" value={answers.certOwnerName.trim() || answers.name} />
                <ReviewRow label="Source ranges" value={answers.sourceRanges || "0.0.0.0/0"} />
                <ReviewRow label="Admin user" value={answers.adminUsername} />
              </div>
              <p className="muted" style={{ fontSize: 12.5 }}>
                Cost estimate: ~$13/mo per endpoint ({answers.vmSize} VM + static IP). Managed Azure VPN Gateway would be ~$140/mo.
              </p>
              {serverError && <p style={{ fontSize: 12.5, color: "var(--danger)" }} role="alert">{serverError}</p>}
            </div>
          )}

          <div className="row gap-2" style={{ justifyContent: "space-between", alignItems: "center" }}>
            <Btn variant="ghost" onClick={() => setPageIdx((i) => Math.max(0, i - 1))} disabled={pageIdx === 0 || submit.isPending}>Back</Btn>
            {onReview ? (
              <Btn variant="primary" icon="plus" loading={submit.isPending} onClick={handleCreate}>Create VPN</Btn>
            ) : (
              <Btn variant="primary" onClick={() => !pageHasError && setPageIdx((i) => Math.min(PAGE_TITLES.length - 1, i + 1))} disabled={pageHasError}>Next</Btn>
            )}
          </div>
        </div>
      </Block.Body>
    </Block>
  );
}

function ReviewRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="row between" style={{ gap: 12, fontSize: 13 }}>
      <span className="muted">{label}</span>
      <span style={{ fontWeight: 600, textAlign: "right", wordBreak: "break-all" }}>{value}</span>
    </div>
  );
}
