/**
 * Scaffolding-file generators for the "Generate & commit" cards of the
 * Deployment Plan panel. Pure string builders — deterministic, stack-keyed,
 * no model in the loop. Kept deliberately minimal-but-production-shaped:
 * multi-stage Dockerfiles, a build+Trivy CI workflow, .env.example from the
 * extracted var list, and a starter README.
 */
import type { DetectedService, EnvVarInfo, RepoAnalysisReport } from "./repo-analyzer";

export function dockerfileFor(service: DetectedService): string {
  switch (service.stack) {
    case "nextjs":
      return `# Multi-stage Next.js build — generated by DeepAgent
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
EXPOSE ${service.port ?? 3000}
CMD ["npm", "start"]
`;
    case "react":
      return `# Static React build served by nginx — generated by DeepAgent
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
    case "node":
      return `# Node.js service — generated by DeepAgent
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE ${service.port ?? 8000}
CMD ["node", "index.js"]
`;
    case "python":
      return `# Python service — generated by DeepAgent
FROM python:3.12-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE ${service.port ?? 8000}
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${service.port ?? 8000}"]
`;
    case "go":
      return `# Go service — generated by DeepAgent
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/app .

FROM gcr.io/distroless/static
COPY --from=build /bin/app /app
EXPOSE ${service.port ?? 8080}
ENTRYPOINT ["/app"]
`;
    default:
      return `# Generated by DeepAgent — adjust for your stack
FROM alpine:3.20
WORKDIR /app
COPY . .
CMD ["sh", "-c", "echo 'configure your runtime'"]
`;
  }
}

export const DOCKERIGNORE = `node_modules
.git
.next
dist
build
__pycache__
*.pyc
.env
.env.*
!.env.example
coverage
*.log
`;

// NOTE: no CI-workflow generator here on purpose — CI/CD pipelines are owned
// by the in-project deploy flow (deploy_my_app / CI-CD tab), which wires the
// registry auth, kubeconfig secrets and CD stages the bare analysis can't.

export function envExampleFor(envVars: EnvVarInfo[]): string {
  const lines = [
    "# Environment variables this app reads — generated by DeepAgent from the source.",
    "# Copy to .env and fill in real values. Secrets marked with (secret).",
    "",
  ];
  for (const v of envVars) {
    lines.push(`${v.name}=${v.secret ? " # (secret)" : ""}`);
  }
  return lines.join("\n") + "\n";
}

// NOTE: no README generator on purpose — the README is the developer's to
// write. The analysis step treats a missing README as a BLOCKER (the agent
// reads it to understand the application before sizing the deployment), so
// generating a hollow one here would defeat the gate.
