/**
 * AWS S3 Bucket Terraform generator.
 *
 * Same shape as lib/devops/rds.ts / eks.ts — a `buildS3Terraform(spec)` that
 * returns a path→HCL map ready to hand to `run_terraform`. Defaults are
 * SECURE-FIRST — public access blocked at every layer, SSE encryption on,
 * versioning on. The caller (generate_s3_terraform tool) validates the
 * spec + AWS creds before this ever runs, so this file trusts its input.
 *
 * The emitted stack:
 *   - random_id (optional 6-byte suffix, when the caller opts in for uniqueness)
 *   - aws_s3_bucket                         (the bucket itself)
 *   - aws_s3_bucket_versioning              (on by default)
 *   - aws_s3_bucket_server_side_encryption_configuration (AES256 or KMS)
 *   - aws_s3_bucket_public_access_block     (ALL four flags true — no public)
 *   - aws_s3_bucket_lifecycle_configuration (only when noncurrentVersionExpirationDays set)
 *   - Two outputs: `bucket` (name) and `arn`.
 *
 * NOT emitted by design: bucket policy, static-website hosting, ACLs, cross-
 * region replication — those are separate feature requests, not sensible
 * defaults. Add as follow-up specs when needed.
 */

export type S3Encryption =
  | { kind: "AES256" }
  | { kind: "aws:kms"; kmsKeyId?: string };

export type S3Spec = {
  /** Bucket name (DNS-safe, globally unique across ALL AWS). 3-63 chars, no uppercase. */
  name: string;
  region: string;
  /** Env key (dev / staging / prod) — used for tagging only. */
  env?: string;
  /** Enable object versioning. Default true. */
  versioning?: boolean;
  /** Encryption — SSE-S3 (AES256) is the sensible default; KMS if the user picked it. */
  encryption?: S3Encryption;
  /** Days after which noncurrent versions expire. Omit to skip the lifecycle rule entirely. */
  noncurrentVersionExpirationDays?: number;
  /** Days after which incomplete multipart uploads are aborted. Default 7 when a lifecycle rule exists. */
  abortIncompleteMultipartDays?: number;
  /** Add a random 6-byte hex suffix to the bucket name (helps avoid the global-uniqueness collision). */
  addRandomSuffix?: boolean;
  /** Additional tags merged in on top of the app's defaults. */
  tags?: Record<string, string>;
};

export const S3_DEFAULTS = {
  versioning: true,
  encryption: { kind: "AES256" } as S3Encryption,
  abortIncompleteMultipartDays: 7,
  addRandomSuffix: false,
} as const;

/**
 * S3 bucket naming rules — validated here so the caller can fail loudly BEFORE
 * we run terraform, not after `aws s3api` rejects it. AWS: 3-63 chars,
 * lowercase alphanumerics + dashes + dots, must start/end with alphanumeric,
 * no consecutive dots, no IP-address-shaped names.
 */
export function validateBucketName(name: string): { ok: true } | { ok: false; error: string } {
  if (name.length < 3 || name.length > 63) {
    return { ok: false, error: "Bucket name must be 3-63 characters." };
  }
  if (!/^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$/.test(name)) {
    return {
      ok: false,
      error: "Bucket name must be lowercase alphanumerics, dashes or dots, starting and ending with a letter or digit.",
    };
  }
  if (/\.\./.test(name)) return { ok: false, error: "Bucket name cannot contain consecutive dots." };
  if (/^\d+\.\d+\.\d+\.\d+$/.test(name)) {
    return { ok: false, error: "Bucket name cannot look like an IP address." };
  }
  return { ok: true };
}

/** Build the full HCL tree ready to hand to `run_terraform`. */
export function buildS3Terraform(spec: S3Spec): Record<string, string> {
  const versioning = spec.versioning ?? S3_DEFAULTS.versioning;
  const encryption = spec.encryption ?? S3_DEFAULTS.encryption;
  const addSuffix = spec.addRandomSuffix ?? S3_DEFAULTS.addRandomSuffix;
  const abortDays = spec.abortIncompleteMultipartDays ?? S3_DEFAULTS.abortIncompleteMultipartDays;
  const hasLifecycle =
    typeof spec.noncurrentVersionExpirationDays === "number" && spec.noncurrentVersionExpirationDays > 0;

  const tags = {
    ManagedBy: "DeepAgent",
    Bucket: spec.name,
    ...(spec.env ? { Environment: spec.env } : {}),
    ...(spec.tags ?? {}),
  };

  const bucketNameExpr = addSuffix
    ? `"${spec.name}-\${random_id.suffix.hex}"`
    : `"${spec.name}"`;

  const versionsTf = `terraform {
  required_version = ">= 1.4"
  required_providers {
    aws    = { source = "hashicorp/aws",    version = "~> 5.60" }
    random = { source = "hashicorp/random", version = "~> 3.6" }
  }
}

provider "aws" {
  region = "${spec.region}"
}
`;

  const mainBlocks: string[] = [];
  mainBlocks.push(
    `# S3 bucket ${spec.name}
# Secure defaults: public access blocked, ${encryption.kind === "AES256" ? "SSE-S3 (AES256)" : "SSE-KMS"} encryption, versioning ${versioning ? "on" : "off"}.
# Generated by DeepAgent. Rerunning the wizard regenerates this file.`,
  );

  if (addSuffix) {
    mainBlocks.push(`resource "random_id" "suffix" {
  byte_length = 3
}`);
  }

  // NOTE: HCL comments in this template MUST NOT contain literal backticks —
  // this whole string is a JS template literal, and a stray backtick would
  // silently close it. (Learned the hard way in lib/devops/rds.ts.)
  mainBlocks.push(`resource "aws_s3_bucket" "this" {
  bucket        = ${bucketNameExpr}
  # force_destroy is intentionally false. An accidental terraform destroy on
  # a bucket that still holds objects will fail loudly instead of nuking them.
  force_destroy = false
  tags          = ${jsonToHcl(tags)}
}`);

  mainBlocks.push(`resource "aws_s3_bucket_public_access_block" "this" {
  bucket                  = aws_s3_bucket.this.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}`);

  mainBlocks.push(`resource "aws_s3_bucket_versioning" "this" {
  bucket = aws_s3_bucket.this.id
  versioning_configuration {
    status = "${versioning ? "Enabled" : "Suspended"}"
  }
}`);

  const encRule =
    encryption.kind === "AES256"
      ? `      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }`
      : `      apply_server_side_encryption_by_default {
        sse_algorithm     = "aws:kms"
        ${encryption.kmsKeyId ? `kms_master_key_id = "${encryption.kmsKeyId}"` : "# kms_master_key_id omitted -> AWS managed alias/aws/s3"}
      }
      bucket_key_enabled = true`;
  mainBlocks.push(`resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  bucket = aws_s3_bucket.this.id
  rule {
${encRule}
  }
}`);

  if (hasLifecycle) {
    mainBlocks.push(`resource "aws_s3_bucket_lifecycle_configuration" "this" {
  bucket = aws_s3_bucket.this.id

  # Wait for versioning to be applied before AWS accepts a lifecycle rule
  # that references noncurrent versions.
  depends_on = [aws_s3_bucket_versioning.this]

  rule {
    id     = "expire-noncurrent"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = ${spec.noncurrentVersionExpirationDays}
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = ${abortDays}
    }
  }
}`);
  }

  const outputsTf = `output "bucket" {
  value       = aws_s3_bucket.this.id
  description = "Name of the created S3 bucket"
}

output "arn" {
  value       = aws_s3_bucket.this.arn
  description = "ARN of the created S3 bucket"
}

output "region" {
  value       = "${spec.region}"
  description = "Region the bucket lives in"
}
`;

  return {
    "main.tf": mainBlocks.join("\n\n") + "\n",
    "outputs.tf": outputsTf,
    "versions.tf": versionsTf,
  };
}

// ── helpers ─────────────────────────────────────────────────────────────

/** Emit a small object as HCL — used only for the tags block. */
function jsonToHcl(obj: Record<string, string>): string {
  const rows = Object.entries(obj).map(([k, v]) => `    ${JSON.stringify(k)} = ${JSON.stringify(v)}`);
  return "{\n" + rows.join("\n") + "\n  }";
}
