apiVersion: v1
kind: Service
metadata:
  name: deep-devops-agent-frontend
  namespace: devo
  annotations:
    "service.beta.kubernetes.io/azure-dns-label-name": deep-devops-agent-frontend
  labels:
    app.kubernetes.io/name: deep-devops-agent-frontend
    app.kubernetes.io/managed-by: deepagent
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: deep-devops-agent-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
