import type { Tool } from "./types";

/**
 * Azure managed database (PostgreSQL / MySQL Flexible Server) Terraform
 * generator — the Azure counterpart to generate_rds_terraform.
 *
 * WHY THIS EXISTS: the app could create an AWS RDS but had no way to create
 * an Azure database at all — only to CONNECT one that already existed. So on
 * an Azure project "create a database" had nowhere to go, and the agent
 * ended up telling users the platform couldn't do it (2026-08). AWS-only
 * database provisioning is not a reasonable answer for a multi-cloud product.
 *
 * Flexible Server rather than Single Server: Single Server is retired by
 * Azure, and Flexible is the only variant that supports VNet integration,
 * which is what lets the AKS cluster reach the database privately.
 *
 * Security defaults, deliberately not optional:
 *   - TLS required (ssl_enforcement / require_secure_transport)
 *   - public network access OFF when a delegated subnet is supplied
 *   - firewall rule for Azure services only when the user chooses public
 *   - 7-day backup retention (Azure's minimum is 1; 7 is the sane floor)
 *
 * The generated files are handed to run_terraform exactly like the AWS path,
 * so the approval gate, cost estimate and state handling are unchanged.
 */

export const AZURE_PG_VERSIONS = ["16", "15", "14", "13"] as const;
export const AZURE_MYSQL_VERSIONS = ["8.0.21", "5.7"] as const;

/** Burstable tiers first — the cheapest thing that actually works for dev. */
export const AZURE_DB_SKUS = [
  "B_Standard_B1ms", // 1 vCPU  / 2 GiB  — dev
  "B_Standard_B2s", // 2 vCPU  / 4 GiB  — small staging
  "GP_Standard_D2s_v3", // 2 vCPU  / 8 GiB  — general purpose
  "GP_Standard_D4s_v3", // 4 vCPU  / 16 GiB — prod baseline
] as const;

type GenInput = {
  name: string;
  envKey: string;
  location: string;
  resourceGroup: string;
  engine: "postgres" | "mysql";
  engineVersion?: string;
  skuName?: string;
  storageMb?: number;
  adminUsername?: string;
  /** Delegated subnet ID for private VNet access. Omit for a public endpoint. */
  delegatedSubnetId?: string;
  privateDnsZoneId?: string;
  highAvailability?: boolean;
};

type GenOutput = {
  files: Record<string, string>;
  stack: string;
  summary: string;
  nextSteps: string[];
};

const DEFAULTS = {
  postgres: { version: "16", port: 5432 },
  mysql: { version: "8.0.21", port: 3306 },
} as const;

function tfvars(i: GenInput): string {
  const engineVersion = i.engineVersion || DEFAULTS[i.engine].version;
  return [
    `name              = "${i.name}"`,
    `environment       = "${i.envKey}"`,
    `location          = "${i.location}"`,
    `resource_group    = "${i.resourceGroup}"`,
    `engine_version    = "${engineVersion}"`,
    `sku_name          = "${i.skuName || "B_Standard_B1ms"}"`,
    `storage_mb        = ${i.storageMb ?? 32768}`,
    `admin_username    = "${i.adminUsername || "dbadmin"}"`,
    `high_availability = ${i.highAvailability ? "true" : "false"}`,
    i.delegatedSubnetId ? `delegated_subnet_id = "${i.delegatedSubnetId}"` : `delegated_subnet_id = ""`,
    i.privateDnsZoneId ? `private_dns_zone_id = "${i.privateDnsZoneId}"` : `private_dns_zone_id = ""`,
  ].join("\n");
}

function mainTf(engine: "postgres" | "mysql"): string {
  const isPg = engine === "postgres";
  const resource = isPg
    ? "azurerm_postgresql_flexible_server"
    : "azurerm_mysql_flexible_server";
  const dbResource = isPg
    ? "azurerm_postgresql_flexible_server_database"
    : "azurerm_mysql_flexible_server_database";
  const fwResource = isPg
    ? "azurerm_postgresql_flexible_server_firewall_rule"
    : "azurerm_mysql_flexible_server_firewall_rule";

  return `terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = { source = "hashicorp/azurerm", version = "~> 3.100" }
    random  = { source = "hashicorp/random",  version = "~> 3.6" }
  }
}

provider "azurerm" {
  features {}
}

# Generated by the platform, not hand-written. The admin password is created
# here and surfaced as a sensitive output — it is NEVER written into the HCL,
# so the file is safe to commit to the repo.
resource "random_password" "admin" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "${resource}" "this" {
  name                = "\${var.name}-\${var.environment}"
  resource_group_name = var.resource_group
  location            = var.location
  version             = var.engine_version

  administrator_login    = var.admin_username
  administrator_password = random_password.admin.result

  sku_name   = var.sku_name
  storage_mb = var.storage_mb

  backup_retention_days = 7

  # Private VNet integration when a delegated subnet is supplied. Azure
  # requires public access to be OFF in that mode — the two are mutually
  # exclusive, and setting both is a plan-time error rather than a warning.
  delegated_subnet_id = var.delegated_subnet_id != "" ? var.delegated_subnet_id : null
  private_dns_zone_id = var.private_dns_zone_id != "" ? var.private_dns_zone_id : null

  dynamic "high_availability" {
    for_each = var.high_availability ? [1] : []
    content {
      mode = "ZoneRedundant"
    }
  }

  lifecycle {
    # The password is rotated out-of-band (see create_rds_k8s_secret's Azure
    # twin); a Terraform re-apply must not reset it and break running pods.
    ignore_changes = [administrator_password, zone]
  }

  tags = {
    Environment = var.environment
    ManagedBy   = "DeepAgent"
  }
}

resource "${dbResource}" "app" {
  name      = replace(var.name, "-", "_")
  server_id = ${resource}.this.id
${isPg ? '  charset   = "UTF8"\n  collation = "en_US.utf8"' : '  charset   = "utf8mb4"\n  collation = "utf8mb4_unicode_ci"'}

  lifecycle {
    prevent_destroy = true
  }
}

# Only meaningful for a PUBLIC server. With a delegated subnet the server has
# no public endpoint and this rule is skipped entirely.
resource "${fwResource}" "azure_services" {
  count            = var.delegated_subnet_id == "" ? 1 : 0
  name             = "allow-azure-services"
  server_id        = ${resource}.this.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "0.0.0.0"
}
${
  isPg
    ? `
# Force TLS. Azure defaults require_secure_transport to ON for Postgres
# Flexible, but it is settable — pin it so a console change can't silently
# downgrade every connection.
resource "azurerm_postgresql_flexible_server_configuration" "require_ssl" {
  name      = "require_secure_transport"
  server_id = ${resource}.this.id
  value     = "ON"
}
`
    : `
resource "azurerm_mysql_flexible_server_configuration" "require_ssl" {
  name      = "require_secure_transport"
  server_id = ${resource}.this.id
  value     = "ON"
}
`
}`;
}

const VARIABLES_TF = `variable "name"                { type = string }
variable "environment"         { type = string }
variable "location"            { type = string }
variable "resource_group"      { type = string }
variable "engine_version"      { type = string }
variable "sku_name"            { type = string }
variable "storage_mb"          { type = number }
variable "admin_username"      { type = string }
variable "high_availability"   { type = bool   default = false }
variable "delegated_subnet_id" { type = string default = "" }
variable "private_dns_zone_id" { type = string default = "" }
`;

function outputsTf(engine: "postgres" | "mysql"): string {
  const resource =
    engine === "postgres"
      ? "azurerm_postgresql_flexible_server"
      : "azurerm_mysql_flexible_server";
  const port = DEFAULTS[engine].port;
  const scheme = engine === "postgres" ? "postgresql" : "mysql";
  return `output "fqdn" {
  value = ${resource}.this.fqdn
}

output "admin_username" {
  value = var.admin_username
}

output "admin_password" {
  value     = random_password.admin.result
  sensitive = true
}

output "database_name" {
  value = replace(var.name, "-", "_")
}

output "port" {
  value = ${port}
}

# Ready to paste into the app's Secret. sslmode=require is not optional —
# Azure rejects non-TLS connections, and omitting it produces a connection
# error that names TLS nowhere.
output "database_url" {
  value     = "${scheme}://\${var.admin_username}:\${urlencode(random_password.admin.result)}@\${${resource}.this.fqdn}:${port}/\${replace(var.name, "-", "_")}?sslmode=require"
  sensitive = true
}
`;
}

export const generateAzureDbTerraformTool: Tool<GenInput, GenOutput> = {
  name: "generate_azure_db_terraform",
  description:
    "Generate Terraform for an Azure Database — PostgreSQL or MySQL Flexible Server. " +
    "This is the AZURE counterpart to generate_rds_terraform: use it whenever the user asks to " +
    "CREATE a database on an Azure project. NEVER hand-write Azure DB HCL — always call this. " +
    "Defaults are secure: TLS enforced, 7-day backups, public access off when a delegated subnet " +
    "is given. The admin password is generated by Terraform and returned as a sensitive output, " +
    "never written into the files. Returns the .tf set; pair with run_terraform(action='plan') then " +
    "the approval gate to provision. AFTER apply, read the database_url output and write it into " +
    "the app's Secret so pods can reach it.",
  inputSchema: {
    type: "object",
    properties: {
      name: {
        type: "string",
        description: "DNS-safe server name (lowercase, dashes). Becomes <name>-<envKey> in Azure.",
      },
      envKey: { type: "string", description: "Env key (dev / staging / prod) — used for naming + tags." },
      location: { type: "string", description: "Azure region, e.g. eastus, westeurope." },
      resourceGroup: { type: "string", description: "EXISTING resource group to create the server in." },
      engine: { type: "string", enum: ["postgres", "mysql"], description: "Database engine." },
      engineVersion: {
        type: "string",
        description: `Engine version. Postgres: ${AZURE_PG_VERSIONS.join(", ")}. MySQL: ${AZURE_MYSQL_VERSIONS.join(", ")}. Defaults to the newest.`,
      },
      skuName: {
        type: "string",
        description: `Compute tier. Options: ${AZURE_DB_SKUS.join(", ")}. Defaults to B_Standard_B1ms (cheapest, fine for dev).`,
      },
      storageMb: { type: "number", description: "Storage in MB. Default 32768 (32 GiB); Azure minimum is 32768." },
      adminUsername: { type: "string", description: "Admin login. Default 'dbadmin'. Cannot be 'azure_superuser' or 'admin'." },
      delegatedSubnetId: {
        type: "string",
        description:
          "Full resource ID of a subnet DELEGATED to the DB service, for private VNet access from AKS. " +
          "Omit for a public endpoint. Strongly preferred for production.",
      },
      privateDnsZoneId: {
        type: "string",
        description: "Private DNS zone resource ID. Required alongside delegatedSubnetId for name resolution.",
      },
      highAvailability: {
        type: "boolean",
        description: "Zone-redundant HA. Roughly doubles cost — only for prod. Not supported on Burstable (B_*) SKUs.",
      },
    },
    required: ["name", "envKey", "location", "resourceGroup", "engine"],
    additionalProperties: false,
  },
  async execute(input) {
    // HA is unavailable on Burstable tiers; Azure fails the apply rather than
    // downgrading, so catch it here where we can explain why.
    const sku = input.skuName || "B_Standard_B1ms";
    if (input.highAvailability && sku.startsWith("B_")) {
      return {
        ok: false,
        error: `High availability isn't supported on the Burstable tier (${sku}). Choose a GP_* SKU — e.g. GP_Standard_D2s_v3 — or set highAvailability=false.`,
      };
    }
    if (input.delegatedSubnetId && !input.privateDnsZoneId) {
      return {
        ok: false,
        error:
          "A delegated subnet also needs privateDnsZoneId — without it the server gets no resolvable name and pods can't connect. " +
          "Pass both, or omit delegatedSubnetId for a public endpoint.",
      };
    }

    const stack = `azure-db-${input.name}-${input.envKey}`;
    const dir = `terraform/azure-db/${input.envKey}`;
    const files: Record<string, string> = {
      [`${dir}/main.tf`]: mainTf(input.engine),
      [`${dir}/variables.tf`]: VARIABLES_TF,
      [`${dir}/outputs.tf`]: outputsTf(input.engine),
      [`${dir}/terraform.tfvars`]: tfvars(input),
    };

    const priv = input.delegatedSubnetId ? "private (VNet-integrated)" : "public endpoint";
    return {
      ok: true,
      output: {
        files,
        stack,
        summary:
          `Azure ${input.engine === "postgres" ? "PostgreSQL" : "MySQL"} Flexible Server ` +
          `"${input.name}-${input.envKey}" in ${input.resourceGroup} (${input.location}), ` +
          `${sku}, ${(input.storageMb ?? 32768) / 1024} GiB, ${priv}, TLS enforced, 7-day backups` +
          `${input.highAvailability ? ", zone-redundant HA" : ""}.`,
        nextSteps: [
          `1. estimate_infra_cost with cloud:'azure', instanceType:'${sku}', storageGb:${(input.storageMb ?? 32768) / 1024} — show the monthly figure before applying.`,
          `2. run_terraform(envKey:'${input.envKey}', name:'${stack}-plan', action:'plan', files:<returned>, stack:'${stack}').`,
          `3. request_infra_approval with the SAME files + stack — never run_terraform apply directly.`,
          `4. After apply, read the 'database_url' output (sensitive) and write it into the app's Secret via apply_app_env_secret so pods pick it up.`,
          input.delegatedSubnetId
            ? `5. Confirm the AKS node subnet can reach the delegated subnet — private servers are unreachable from outside the VNet by design.`
            : `5. This server has a PUBLIC endpoint with an allow-Azure-services rule. For production, re-run with delegatedSubnetId + privateDnsZoneId.`,
        ],
      },
    };
  },
};
