/**
 * Jenkinsfile generator — produces the pipeline Groovy for build → scan → push
 * → deploy, matching the GitHub Actions equivalent from ci-workflow / cd-workflow.
 *
 * The agent generates ONE Jenkinsfile per app service (monorepo = multiple)
 * and commits it directly to the repo's default branch. Jenkins picks it up
 * via the standard multibranch pipeline pattern.
 */

export type JenkinsCloud = "aws" | "azure" | "gcp";

export type JenkinsfileSpec = {
  /** Human app name, used for k8s Deployment + Jenkins job name. */
  appName: string;
  /** Build-context subdir; "" for repo root. */
  context: string;
  /** Registry URI up to but not including the tag (e.g. 123.dkr.ecr.us-east-1.amazonaws.com/api). */
  registryUri: string;
  /** Cloud powering the registry — decides the docker-login block. */
  cloud: JenkinsCloud;
  /** Region for cloud CLIs (AWS) or ACR name (Azure) — passed as env. */
  cloudRegion?: string;
  /** k8s namespace to deploy into. */
  namespace: string;
  /** Env this deploys to (dev / staging / prod). Used for branch guards. */
  env: string;
  /** Whether Trivy HIGH/CRITICAL should fail the build. Default true. */
  scanGate?: boolean;
  /** Cluster identifier — plumbed into the deploy stage (aws eks update-kubeconfig args, etc.). */
  clusterName?: string;
  /** Credential IDs already set up in Jenkins credential store. */
  credentials: {
    /**
     * Cloud auth. For AWS: a "usernamePassword" credential where the username
     * is the access key id and the password is the secret access key. Or a
     * "string" credential holding a role ARN if using IRSA-in-pod.
     */
    cloud: string;
    /** Kubeconfig — a "file" credential type. */
    kubeconfig: string;
    /** Optional Slack webhook token for notifications. */
    slackWebhook?: string;
  };
  /** Optional container port for the Deployment patch. Default 3000. */
  containerPort?: number;
  /** Deployment method — 'manifests' uses kubectl apply, 'helm' uses helm upgrade. */
  manifestType?: "manifests" | "helm";
  /** Helm-only: chart path inside the repo. */
  chartPath?: string;
  /** Helm-only: release name. */
  releaseName?: string;
};

/** The Jenkinsfile Groovy for one service. Returns the file body verbatim. */
export function generateJenkinsfile(spec: JenkinsfileSpec): string {
  const ctxPrefix = spec.context ? `${spec.context.replace(/^\/+|\/+$/g, "")}/` : "";
  const scanBlock = generateScanStage(spec.scanGate !== false, ctxPrefix);
  const pushBlock = generatePushStage(spec.cloud, spec.registryUri, ctxPrefix, spec.credentials.cloud, spec.cloudRegion);
  const deployBlock = spec.manifestType === "helm"
    ? generateHelmDeployStage(spec)
    : generateKubectlDeployStage(spec, ctxPrefix);
  const notifyBlock = generateNotifyBlock(spec.credentials.slackWebhook);

  return `// Generated by DeepAgent — pipeline for ${spec.appName} → ${spec.env}
// Edit with care: rerunning the wizard rewrites this file.
pipeline {
  agent any
  options {
    timestamps()
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr: '20'))
    disableConcurrentBuilds()
  }
  environment {
    APP_NAME     = '${spec.appName}'
    IMAGE_REPO   = '${spec.registryUri}'
    IMAGE_TAG    = "\${env.GIT_COMMIT?.take(7) ?: env.BUILD_NUMBER}"
    IMAGE_REF    = "\${IMAGE_REPO}:\${IMAGE_TAG}"
    K8S_NAMESPACE = '${spec.namespace}'
    ENV_KEY       = '${spec.env}'
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Build image') {
      steps {
        sh '''
          set -eux
          docker build -t "\${IMAGE_REF}" ${spec.context || "."}
        '''
      }
    }
${scanBlock}
${pushBlock}
${deployBlock}
  }
${notifyBlock}
}
`;
}

function generateScanStage(gate: boolean, _ctxPrefix: string): string {
  const exit = gate ? "1" : "0";
  return `    stage('Scan (Trivy)') {
      steps {
        sh '''
          set -eux
          if ! command -v trivy >/dev/null 2>&1; then
            echo "trivy not on PATH — install it on this Jenkins agent."
            exit 1
          fi
          trivy image --severity HIGH,CRITICAL --exit-code ${exit} --no-progress "\${IMAGE_REF}"
        '''
      }
    }`;
}

function generatePushStage(cloud: JenkinsCloud, _uri: string, _ctx: string, credId: string, region?: string): string {
  if (cloud === "aws") {
    return `    stage('Push to ECR') {
      steps {
        withCredentials([usernamePassword(credentialsId: '${credId}', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          sh '''
            set -eux
            aws ecr get-login-password --region ${region ?? "us-east-1"} \\
              | docker login --username AWS --password-stdin "\${IMAGE_REPO}"
            docker push "\${IMAGE_REF}"
          '''
        }
      }
    }`;
  }
  if (cloud === "azure") {
    // For ACR — the ${uri} looks like <acr-name>.azurecr.io/<repo>
    return `    stage('Push to ACR') {
      steps {
        withCredentials([usernamePassword(credentialsId: '${credId}', usernameVariable: 'ACR_USERNAME', passwordVariable: 'ACR_PASSWORD')]) {
          sh '''
            set -eux
            # ACR host is everything before the first '/' in IMAGE_REPO.
            ACR_HOST=$(echo "\${IMAGE_REPO}" | cut -d/ -f1)
            echo "\${ACR_PASSWORD}" | docker login "\${ACR_HOST}" --username "\${ACR_USERNAME}" --password-stdin
            docker push "\${IMAGE_REF}"
          '''
        }
      }
    }`;
  }
  // GCP Artifact Registry
  return `    stage('Push to Artifact Registry') {
      steps {
        withCredentials([file(credentialsId: '${credId}', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
          sh '''
            set -eux
            REGION=$(echo "\${IMAGE_REPO}" | cut -d- -f1)
            gcloud auth activate-service-account --key-file="\${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud auth configure-docker "\${REGION}-docker.pkg.dev" --quiet
            docker push "\${IMAGE_REF}"
          '''
        }
      }
    }`;
}

function generateKubectlDeployStage(spec: JenkinsfileSpec, _ctxPrefix: string): string {
  return `    stage('Deploy (kubectl)') {
      when { branch pattern: 'main|master', comparator: 'REGEXP' }
      steps {
        withCredentials([file(credentialsId: '${spec.credentials.kubeconfig}', variable: 'KUBECONFIG')]) {
          sh '''
            set -eux
            kubectl -n "\${K8S_NAMESPACE}" apply -f k8s/${spec.env}/
            kubectl -n "\${K8S_NAMESPACE}" set image deployment/"\${APP_NAME}" "\${APP_NAME}=\${IMAGE_REF}"
            kubectl -n "\${K8S_NAMESPACE}" rollout status deployment/"\${APP_NAME}" --timeout=5m
          '''
        }
      }
    }`;
}

function generateHelmDeployStage(spec: JenkinsfileSpec): string {
  const chart = (spec.chartPath || `charts/${spec.appName}/`).replace(/\/+$/, "") + "/";
  const release = spec.releaseName || `${spec.appName}-${spec.env}`;
  return `    stage('Deploy (Helm)') {
      when { branch pattern: 'main|master', comparator: 'REGEXP' }
      steps {
        withCredentials([file(credentialsId: '${spec.credentials.kubeconfig}', variable: 'KUBECONFIG')]) {
          sh '''
            set -eux
            helm upgrade --install "${release}" "${chart}" \\
              --namespace "\${K8S_NAMESPACE}" --create-namespace \\
              -f ${chart}values.yaml \\
              -f ${chart}values-\${ENV_KEY}.yaml \\
              --set image.repository="\${IMAGE_REPO}" \\
              --set image.tag="\${IMAGE_TAG}" \\
              --wait --timeout 5m
          '''
        }
      }
    }`;
}

function generateNotifyBlock(slackCredentialId?: string): string {
  const slackOk = slackCredentialId
    ? `slackSend(channel: '#deploys', color: 'good', message: "✓ \${env.APP_NAME} → \${env.ENV_KEY}: \${env.IMAGE_TAG} (\${env.BUILD_URL})", tokenCredentialId: '${slackCredentialId}')`
    : "echo 'Deploy succeeded — configure Slack credential id to notify a channel.'";
  const slackBad = slackCredentialId
    ? `slackSend(channel: '#deploys', color: 'danger', message: "✗ \${env.APP_NAME} → \${env.ENV_KEY} FAILED: \${env.BUILD_URL}", tokenCredentialId: '${slackCredentialId}')`
    : "echo 'Deploy failed — configure Slack credential id to notify a channel.'";
  return `  post {
    success {
      ${slackOk}
    }
    failure {
      ${slackBad}
    }
  }`;
}

/** Jenkins pipeline job config.xml — installs the pipeline against a repo SCM. */
export function generatePipelineConfigXml(opts: {
  description: string;
  repoUrl: string;
  branch: string;
  jenkinsfilePath: string;
  /** GitHub/GitLab credentials id in Jenkins credentials store for HTTPS clone. */
  scmCredentialsId?: string;
}): string {
  const scmCreds = opts.scmCredentialsId
    ? `<credentialsId>${escapeXml(opts.scmCredentialsId)}</credentialsId>`
    : "";
  return `<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job">
  <description>${escapeXml(opts.description)}</description>
  <keepDependencies>false</keepDependencies>
  <properties>
    <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
      <triggers>
        <hudson.triggers.SCMTrigger><spec>H/5 * * * *</spec></hudson.triggers.SCMTrigger>
      </triggers>
    </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps">
    <scm class="hudson.plugins.git.GitSCM" plugin="git">
      <configVersion>2</configVersion>
      <userRemoteConfigs>
        <hudson.plugins.git.UserRemoteConfig>
          <url>${escapeXml(opts.repoUrl)}</url>
          ${scmCreds}
        </hudson.plugins.git.UserRemoteConfig>
      </userRemoteConfigs>
      <branches>
        <hudson.plugins.git.BranchSpec>
          <name>*/${escapeXml(opts.branch)}</name>
        </hudson.plugins.git.BranchSpec>
      </branches>
      <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
      <submoduleCfg class="empty-list"/>
      <extensions/>
    </scm>
    <scriptPath>${escapeXml(opts.jenkinsfilePath)}</scriptPath>
    <lightweight>true</lightweight>
  </definition>
  <triggers/>
  <disabled>false</disabled>
</flow-definition>`;
}

function escapeXml(s: string): string {
  return s.replace(/[<>&'"]/g, (c) =>
    c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === "&" ? "&amp;" : c === "'" ? "&apos;" : "&quot;",
  );
}
