import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db/prisma";
import { requireProjectAccess } from "@/lib/projects/permissions";
import { buildJenkinsVmTerraform, JENKINS_VM_DEFAULTS } from "@/lib/devops/jenkins-vm";
import { createInfraApproval, type TerraformFile } from "@/lib/devops/infra-approval";
import { writeRepoFileTool } from "@/lib/agent/tools/write-repo-file";

/**
 * POST /projects/[slug]/aws/jenkins/provision
 *
 * One-click Jenkins provisioning:
 *   1. Generate the EC2 + user-data Terraform for a self-configuring Jenkins.
 *   2. Commit each .tf under terraform/jenkins/<name>/.
 *   3. Write a starter Jenkinsfile at the repo root if one doesn't exist yet
 *      (so the user has SOMETHING to point a Jenkins job at post-provision).
 *   4. Create an infra approval; return approvalId for inline ApprovalCard.
 */
const Body = z.object({
  name: z
    .string()
    .trim()
    .regex(/^[a-z][a-z0-9-]{1,40}$/, "Name must be lowercase, dashes, 2-41 chars, starting with a letter."),
  envKey: z.string().trim().min(1),
  region: z.string().trim().min(1),
  vpcId: z.string().trim().min(1),
  subnetId: z.string().trim().min(1),
  instanceType: z.string().trim().optional(),
  diskGb: z.number().int().min(20).max(4096).optional(),
  adminUsername: z.string().trim().min(1).max(64).optional(),
  adminPassword: z.string().min(8, "Admin password must be at least 8 characters."),
  keyName: z.string().trim().optional(),
  sshCidr: z.string().trim().optional(),
  jenkinsCidr: z.string().trim().optional(),
  existingSecurityGroupIds: z
    .array(z.string().trim().regex(/^sg-[0-9a-f]{8,17}$/, "Invalid SG id."))
    .max(5)
    .optional(),
});

// Minimal "hello world" pipeline the wizard drops into the repo when there
// isn't one. Users typically flesh this out post-provision — the point is
// that Jenkins has SOMETHING to build on the first job run.
const STARTER_JENKINSFILE = `// Starter Jenkinsfile generated by DeepAgent.
// Replace the stages below with your real build/test/deploy steps.
pipeline {
  agent any

  options {
    timestamps()
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr: '20'))
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Hello') {
      steps {
        sh 'echo "Hello from Jenkins — running on \${NODE_NAME}"'
        sh 'echo "Commit: \${GIT_COMMIT}"'
      }
    }

    stage('Build') {
      steps {
        echo 'Add your real build steps here (npm run build, mvn package, docker build, …).'
      }
    }

    stage('Test') {
      steps {
        echo 'Add your test steps here.'
      }
    }
  }

  post {
    success { echo '✔ pipeline succeeded' }
    failure { echo '✖ pipeline failed' }
  }
}
`;

export async function POST(req: Request, ctx: { params: Promise<{ slug: string }> }) {
  const { slug } = await ctx.params;
  const gate = await requireProjectAccess(slug, "developer");
  if (!gate.ok) return NextResponse.json({ ok: false }, { status: gate.status });
  const projectId = gate.access.project.id;

  const parsed = Body.safeParse(await req.json().catch(() => ({})));
  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, code: "invalid_request", message: parsed.error.errors[0]?.message },
      { status: 400 },
    );
  }
  const body = parsed.data;

  const cp = await prisma.cloudProvider.findFirst({
    where: { projectId, kind: "aws" },
    select: { id: true },
  });
  if (!cp) {
    return NextResponse.json({ ok: false, code: "no_aws_provider" }, { status: 409 });
  }
  const env = await prisma.env.findFirst({
    where: { projectId, key: body.envKey },
    select: { id: true, key: true },
  });
  if (!env) return NextResponse.json({ ok: false, code: "env_not_found" }, { status: 404 });
  const pr = await prisma.projectRepo.findFirst({
    where: { projectId, repo: { deletedAt: null } },
    orderBy: { addedAt: "desc" },
    select: { repo: { select: { fullName: true, defaultBranch: true } } },
  });
  if (!pr?.repo?.fullName) {
    return NextResponse.json({ ok: false, code: "no_repo", message: "Attach a repo first." }, { status: 409 });
  }
  const repoFullName = pr.repo.fullName;
  const defaultBranch = pr.repo.defaultBranch || "main";

  const files = buildJenkinsVmTerraform({
    name: body.name,
    region: body.region,
    env: body.envKey,
    vpcId: body.vpcId,
    subnetId: body.subnetId,
    instanceType: body.instanceType,
    diskGb: body.diskGb,
    adminUsername: body.adminUsername,
    adminPassword: body.adminPassword,
    keyName: body.keyName,
    sshCidr: body.sshCidr,
    jenkinsCidr: body.jenkinsCidr,
    existingSecurityGroupIds: body.existingSecurityGroupIds,
    tags: { CreatedBy: "deepagent-jenkins-ui" },
  });

  const commits: Array<{ path: string; commitSha: string }> = [];
  for (const [filename, content] of Object.entries(files)) {
    const path = `terraform/jenkins/${body.name}/${filename}`;
    const res = await writeRepoFileTool.execute(
      {
        repoFullName,
        path,
        content,
        message: `Add Jenkins ${body.name} (${body.region})`,
        branch: defaultBranch,
      },
      { projectId, userId: gate.access.session.userId },
    );
    if (!res.ok) {
      return NextResponse.json(
        { ok: false, code: "commit_failed", message: `${path}: ${res.error}` },
        { status: 502 },
      );
    }
    commits.push({ path, commitSha: res.output.commitSha });
  }

  // Starter Jenkinsfile — committed at a safe SIDE-BY-SIDE path
  // (`Jenkinsfile.deepagent-starter`) so we can NEVER clobber an existing
  // Jenkinsfile the user already committed. Rename it to plain "Jenkinsfile"
  // if you want Jenkins to actually run it — the README below tells them so.
  let jenkinsfileCreated = false;
  {
    const res = await writeRepoFileTool.execute(
      {
        repoFullName,
        path: "Jenkinsfile.deepagent-starter",
        content: STARTER_JENKINSFILE,
        message: "Add starter Jenkinsfile (rename to Jenkinsfile to use)",
        branch: defaultBranch,
      },
      { projectId, userId: gate.access.session.userId },
    );
    if (res.ok) {
      jenkinsfileCreated = true;
      commits.push({ path: "Jenkinsfile.deepagent-starter", commitSha: res.output.commitSha });
    }
  }

  const stack = `jenkins-${body.name}`;
  const tfFiles: TerraformFile[] = Object.entries(files).map(([path, content]) => ({ path, content }));
  const approval = await createInfraApproval({
    projectId,
    envId: env.id,
    envKey: env.key,
    title: `Provision Jenkins ${body.name} in ${body.region}`,
    summary: [
      `EC2 ${body.instanceType ?? JENKINS_VM_DEFAULTS.instanceType} with Jenkins pre-installed`,
      `Admin user '${body.adminUsername ?? JENKINS_VM_DEFAULTS.adminUsername}' auto-created`,
      `~$${estimatePriceUSDPerMonth(body.instanceType ?? JENKINS_VM_DEFAULTS.instanceType)}/mo`,
      jenkinsfileCreated ? "starter Jenkinsfile.deepagent-starter committed at repo root" : "no starter file committed (commit failed)",
    ].join(" · ") + ".",
    cloud: "aws",
    region: body.region,
    name: `${stack}-apply`,
    stack,
    files: tfFiles,
    planSummary: [
      { change: "add" as const, text: `aws_instance ${body.instanceType ?? JENKINS_VM_DEFAULTS.instanceType} (Jenkins pre-installed via user-data)` },
      ...(body.existingSecurityGroupIds?.length
        ? [{ change: "add" as const, text: `Attaches existing SG${body.existingSecurityGroupIds.length === 1 ? "" : "s"}: ${body.existingSecurityGroupIds.join(", ")}` }]
        : [{ change: "add" as const, text: "aws_security_group (8080 open" + (body.sshCidr ? ` + 22 open to ${body.sshCidr}` : "") + ")" }]),
      { change: "add" as const, text: "aws_iam_role + instance profile (SSM)" },
      ...(body.keyName ? [{ change: "add" as const, text: `SSH key pair attached: ${body.keyName}` }] : []),
    ],
  });
  if (!approval.ok) {
    return NextResponse.json(
      {
        ok: false,
        code: "policy_blocked",
        message: `Policy blocked this change: ${approval.policy.violations.map((v) => v.message).join(" ")}`,
        violations: approval.policy.violations,
      },
      { status: 400 },
    );
  }
  return NextResponse.json({
    ok: true,
    approvalId: approval.approvalId,
    risk: approval.risk,
    committedFiles: commits,
    repoPath: `terraform/jenkins/${body.name}/`,
    repoFullName,
    jenkinsfileCreated,
  });
}

// Rough on-demand pricing for the most common Jenkins-friendly instance types.
// Real bills vary by region + savings plans; this is a "prevent sticker shock"
// hint on the approval card, not a billing system.
function estimatePriceUSDPerMonth(instanceType: string): number {
  const table: Record<string, number> = {
    "t3.micro": 8,
    "t3.small": 15,
    "t3.medium": 30,
    "t3.large": 60,
    "t3.xlarge": 120,
    "m5.large": 70,
  };
  return table[instanceType] ?? 30;
}
